### ISSUE TITLE
Homepage V1: Feedback and approval

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#109]
## Description:

Finalize and deliver the first version of our community homepage by collecting and incorporating feedback from stakeholders.

### Tasks:

- [x] Gather feedback from stakeholders and community members.
- [x] Implement necessary changes based on feedback.
- [x] Test and validate all changes.
- [x] Prepare and deliver the final version.
- [x] Announce the release to the community.
- [x] Update the link in the qrcodes.

### Requirements:

Web development and design experience.
Strong communication skills.
Attention to detail.

**Comment by marcaumdesign** [comment]
# General

## Hero

- The P size of hero is 1 rem only, for main texts like this one from Hero, I recommend a size of at least 1.25 rem to give greater readability. Additionally, I added a little more text to make two lines and create harmony with the H1, follow the example recommendation

![Image](https://github.com/orgs/w3b3d3v/projects/15/assets/146405199/f308d438-a08e-4dc6-97e3-80ed3a677f23)

- The card's glow effect is above the text, I recommend that it is below the text for good reading

![Image](https://github.com/orgs/w3b3d3v/projects/15/assets/146405199/93a0d2cb-04e0-4fb2-9a31-5ee5169692e6)

## Case Solana

- The color in the "Talent Development" icon is not following the standard like the others, I recommend changing it to blue to follow the standard

![Image](https://github.com/orgs/w3b3d3v/projects/15/assets/146405199/a9c59c0c-287b-4331-80c0-91dd799fd220)

- There is an asymmetry in the number of icons in the "Partners & Clients" CTA, I recommend that one more icon be inserted to maintain maximum harmony

![Image](https://github.com/orgs/w3b3d3v/projects/15/assets/146405199/7f9b6816-2555-4939-b2b4-8f4539891adb)

- The text has a widow word at the maximum size of the card, I recommend that you set the maximum text size to 520px, where this small inconsistency begins to occur.

![Image](https://github.com/orgs/w3b3d3v/projects/15/assets/146405199/13e41c38-76de-4f7f-9ac5-063e5a81685c)

## Footer

- The contrast between the background and the social media icons in the footer has a contrast of 4.11 (according to WCAG), I recommend that we set it to green (#4CE577) to increase it to 11.75

![Image](https://github.com/orgs/w3b3d3v/projects/15/assets/146405199/86a7950c-099c-4c50-bdb4-d742696193d3)

# Responsive

## Hero

- Here the Web3Dev logo does not follow the hierarchy defined in the H1, I recommend placing a relative size on the logo as well to maintain consistency with the Desktop

![Image](https://github.com/orgs/w3b3d3v/projects/15/assets/146405199/fefdbfe1-6fdc-4ce8-9b8a-cea36abaf5e2)

- I also recommend leaving the Mobile H1

![Image](https://github.com/orgs/w3b3d3v/projects/15/assets/146405199/c19cf4c1-dd7b-459a-9ffe-8965dc90cd53)

## Case Solana

- I recommend texts aligned to the center here, as they are not cards like in the section above.

![Image](https://github.com/orgs/w3b3d3v/projects/15/assets/146405199/3ee7e259-82bb-47f2-979b-e8282bc0345f)

- There is some positioning problem here.

![Image](https://github.com/orgs/w3b3d3v/projects/15/assets/146405199/17b3c61e-0d24-48c2-86f2-6837697afc9e)

# Summary

Overall, the page has a pleasant appearance and contains simple information so that it is very easy for the user to understand and digest what Web3Dev is. Other than that, we only have a few small cases that need to be improved to achieve maximum conversion performance on this Landing Page.

**Comment by annabida** [comment]
The English page is already in production: https://www.w3d.community/en
