### ISSUE TITLE
WEB3TASK V2 Roadmap

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/community-management#114]
- [x] Address Kyodo Chain-Agnostic Module.
- [x] Communitcate with previous contributors.
- [x] Define next steps.
- [x] Distribute practical ToDos for next weeks
- [x] Define Routines and schedules.

**Comment by nomadbitcoin** [comment]
- [ ] Figma: List all essential features.
- [ ] Figma: List all desired features.
