### ISSUE TITLE
📊 Competitive Analysis

### ISSUE THREAD

**Issue by marcaumdesign** [w3b3d3v/community-management#118]
# Overview

In every project creation, a good reference base is necessary so that we can reflect on the best aspects and create a solution that serves our target audience very well.

And here in the Branding project it won't be much different, we will also need a competitive analysis to better understand our scenario and make the best decisions when redefining our brand.

# Execution

For this I chose the Competitive Analysis template with a more interesting UX Design:

[Shopify Competitive Analysis Template](https://docs.google.com/spreadsheets/d/1ITn_RKlfBCGodn0CTrMgT1C6tSl1UpBWSbtmhEnHjqM/edit#gid=839935728)

![Image](https://github.com/w3b3d3v/community-management/assets/146405199/3ff2cfea-181e-45fb-94b7-e4bc73014e06)

And basically we have the steps that need to be carried out, which in the end will give us a table that will tell us a lot about the competitive scenario we are experiencing and what projections to take to become one of our best competitors.

As the process is complex, we can choose to do just a few steps, where the last step is the most essential of all.

# Tasks

## 01. Set goals

- [ ] What do you want to get out of competitive research
- [ ] Who are your main competitors?
- [ ] Who are your secondary competitors?

## 02. Search

- [ ] Collect the 5 initial competitors
- [ ] Fill in the table with data from the 5 competitors

## 03. High-Level Competitive Analysis

- [ ] Place the 5 initial competitors
- [ ] Fill in the table with data from the 5 competitors
- [ ] Fill in the table with our data

## 04. Competitor Scorecard

- [ ] Place the 3 initial competitors + our company
- [ ] Give due points to competitors
- [ ] Give due points to our company
