### ISSUE TITLE
Homepage V2: Create the Study Group Page and Menu

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#123]
## Description:

Develop and integrate a new Study Group page and menu into the second version of the community homepage to enhance accessibility and participation in study groups.

## Tasks:
- [x] Create and revise the copy for the page
- [x] Design the layout and structure of the Study Group page.
- [x] Implement the Study Group page on the community homepage.
- [x] Create and integrate a menu for easy navigation to the Study Group page.
- [x] Test the new page and menu for usability and functionality.
- [x] Gather feedback from users and make necessary adjustments.
- [x] Launch the Study Group page and menu.

**Comment by marcaumdesign** [comment]
Internal page example for Study Group page, [open here the picture on Figma.](https://www.figma.com/design/HbnwfL04JWwkvJuCEGowmv/Build-Platform-v2?node-id=26-781&t=A225Db1CA0Dh2XKt-1)

![Image](https://github.com/w3b3d3v/community-management/assets/146405199/c1a75659-17d7-4f58-a88c-1664d9398676)

**Comment by annabida** [comment]
Result: https://www.w3d.community/en/grupos-de-estudos
