### ISSUE TITLE
Brand Book: Creation of 4 personas

### ISSUE THREAD

**Issue by marcaumdesign** [w3b3d3v/community-management#131]
# Overview

Create 4 personas that will be represented as the most abstract types of users that we have today engaging in the community. By understanding and defining these personas, we will know what pain points each person has and how we should act empathetically to help these members.

> Related to task #124

**Comment by nomadbitcoin** [comment]
Research with other developers in the community who can help you create the persona: https://www.figma.com/board/C6xWlHcE94r7ojKvdXxeRo/Ky%C5%8Dd%C5%8D-Protocol---%E5%85%B1%E5%90%8C?node-id=282-774&t=IbIafYCu6Vke2p1V-1

**Comment by marcaumdesign** [comment]
First model created 

![Image](https://github.com/w3b3d3v/community-management/assets/146405199/be01e95e-feef-4b60-b759-4f1b6be83136)

**Comment by marcaumdesign** [comment]
# Tasks

- [x] Complete the Female Student persona
- [x] Complete the Male Group Leader persona
- [x] Complete the Female Group Leader persona

**Comment by marcaumdesign** [comment]
# Delivery

The personas were developed and created, I will be putting a summary of them here, to review them you can access [here at this link.](https://www.figma.com/board/ts0XEHwUWzHOAZsNgH6CoR/Branding?node-id=0-1&t=QP2YUFXD7qnPdmrU-1)

## Study Group Students

1. **Carlos Oliveira:** is a 28-year-old back-end developer, single and living in São Paulo. He is passionate about exploring the infinite possibilities of web3 technology and seeks a community that is welcoming and collaborative.

2. **Julia Santos:** is 29 and a Web3 developer from São Paulo. She is single and with an income of R$8,000, seeking education, certification and networking. She faces challenges finding teaching resources in Portuguese and staying up to date.

## Study Group Leaders

3. **Rafael Costa:** is 32 and a Senior Web3 Developer in Rio de Janeiro. Married, he earns R$12,000.00, seeks out curious students and faces challenges by simplifying complex concepts. Active on technology forums and events.

4. **Ana Beatriz Rocha:** is 34 and a Senior Web3 Developer in Belo Horizonte, single and with an income of R$10,000, aspires to lead in technological education. It faces challenges when simplifying complex concepts and seeks engaged employees. Active on forums, social networks and events.













****
