### ISSUE TITLE
Brand Book: Definition

### ISSUE THREAD

**Issue by marcaumdesign** [w3b3d3v/community-management#132]
# Overview

Define brand proprieties to construct the Brand Book.

# Tasks

- [x] Create logo tests
- [x] Create color tests
- [x] Create typography tests
- [x] Create shape tests

**Comment by marcaumdesign** [comment]
Test of three main elements created, only remaining the shapes



![Image](https://github.com/w3b3d3v/community-management/assets/146405199/d12d284a-95d7-432a-84fd-9e85fa63a683)

**Comment by marcaumdesign** [comment]
# Second Iteration

**Brand:** All the dynamics carried out to evaluate our values ​​and cultures have been carried out, and now the definition is being carried out by Nicholas

**Logo:** The logo will remain the same, even in the face of different variations, the one that best fits the brand's concept is the current one

**Colors:** Since the main theme of Web3Dev is dark (due to the technological theme), green is the best color to be the primary,

And the rest are the highlights for each area, where we need to define the best occasion to use them.

**Typography:** I recommend that we only use Barlow in every project, since it is the logo used in the logo.  What remains is to define how we will use font variations in text bodies and their appropriate sizes.

**Shapes:** The best shapes to use are still being defined and researched, but the best candidates seem to be abstract 3D objects.  Furthermore, it would be interesting to play a little with the logo to make some art patterns for frames and more.

![Image](https://github.com/w3b3d3v/community-management/assets/146405199/c477af11-1549-4d1e-b832-7aa737574c64)

**Comment by marcaumdesign** [comment]
# Third Iteration

## Flat
**Colors**
- [ ] Define a use for each color and recommendations for use

**Typography**
- [x] Defined the use of text hierarchy and title cases (redo some artwork to find the best combination)

**Shapes**
- [ ] Find the best 3D object package for the brand
- [ ] Create design patterns using the shapes of the logo to find a cool pattern for the brand

**Comment by marcaumdesign** [comment]
# Fourth Iteration

Essa é a ultima iteração da versão 1 do Brand Book, onde o estilo será **Flat**, cujo é representado por fotos, tipografia e alguns grafismos, essa decisão foi tomada para acelerarmos a versão final do projeto e ja termos diretrizes suficientes para criarmos e gerarmos artes melhores do que no rebranding antigo.

## Brand

Aqui temos uma definição temporária enquanto @piadascripto termina os valores.

**Missão:** Our mission is to promote free technical education in community.
**Visão:** Our vision is a democratized and decentralized future
**Valores:** Excellence,Transparency, Empathy, Innovation, Sustainability & Diversity

## Logotipo

Sobre o logotipo, ele continuou o mesmo, com uma única mudança no símbolo onde o verde mais claro foi equalizado para o verde menos saturado, razão que iremos discutir no capítulo das cores.

## Cores

Aqui defini a palheta principal com três cores

### Cor Primária

**Verde (#96E150):** Esta cor frequentemente está associada ao crescimento, inovação e vitalidade, o que é ideal para grupos focados em desenvolvimento, sugerindo uma atmosfera de aprendizado contínuo e evolução. Além disso ela entre as três cores que já existiam no Brand Book, é a que mais se sobressai no tema escuro que estamos adotando para a marca. Iremos utilizar o verde para **representar assuntos de desenvolvimento e código.**

### Cores De Destaque

**Azul(#1E96FF):** O azul transmite confiança, estabilidade e profundidade, características essenciais para estudos relacionados ao blockchain, onde a segurança e a confiabilidade são fundamentais. Não conheço o motivo pelo qual o designer escolheu o azul para marca, porém ele encaixa muito bem no tema de educação e tecnologia, pois dá um conforto para para iniciantes aprenderem, e por isso ele será utilizado para **representar assuntos de Blockchain, que são os mais introdutórios nas nossas builds e grupos de estudos.**

**Roxo(#7864FA)**: O roxo é uma cor que simboliza criatividade, misticismo e futuro, muito apropriado para áreas que exploram novas tecnologias e inovações, promovendo um senso de exploração e descoberta. Também não conheço o motivo do designer ter escolhido, porém ele se encaixa muito bem para representar novas tecnologias e inovações que são "mágicas", personalidade que é bem importante para cativar públicos mais entusiastas com Web3. **E por isso ele será utilizado para representar assuntos de Tecnologias inovadoras, como Marcas de Blockchains e IAs.**

E para finalizar eu decidi retirar o tom mais saturado de verde por questões de facilidade de escalabilidade, redução de custos para materiais, minimalismo visual, consistência visual e velocidade de decisões. Uma cor a mais na palheta principal que é semelhante a outra acaba atrapalhando mais do que ajudando a marca a se desenvolver, um bom exemplo é o rebranding do Airbnb em 2014 que reduziu sua palheta e conseguiu atingir a maior parte dos pontos que eu falei no começo

## Tipografia

E para a tipografia eu escolhi a fonte principal como Barlow, cuja é a fonte da logo, apesar de termos no nosso antigo Brand Book a HK Grotesk, ambas são Sans Serif e colocar essas duas na marca daria a mesma sensação que um carro com rodas iguais, mas com calotas diferentes, por mais que o carro ainda ande, a inconsistência seria facilmente notada por aqueles que tem bons olhos.

E a principal definição que eu fiz, foi que para títulos teríamos o estilo da fonte em UltraBold Italic e para parágrafos o estilo da fonte em Medium. 

## Imagery

E para definir a imagery

Natural Photography: Podemos utilizar qualquer tipo de fotografia, porém é interessante darmos espaços a imagens que tenham pelo menos uma das cores das marcas

Artificial Photography: Iremos aqui utilizar imagens que remetam a programação e universo de tecnologia, porém como aqui temos a opção de customizar a imagem, temos que sempre colocar os tons da marca no prompt que a foto for gerada.

Grafismos: por enquanto teremos somente a logo em outline e um grid simples e tecnológico

Ícones: iremos utilizar a biblioteca Phosphor para os ícones gerais da identidade visual

Ilustrações e Elementos: por enquanto não teremos, porém será interessante ter alguns elementos, como moedas e blocos para criarmos mais atenção para a marca.

**Comment by annabida** [comment]
Very good @marcaum-eth 
Could you provide the link to the figma and the drive here before we finalize this issue?
