### ISSUE TITLE
Checklist Creating a new group <Creative Coding>

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#164]
# Study group scheduling task list
## Before event

- [x] Approve proposal for new group  
   - [x] [Fill in the form](https://forms.gle/dgvGgcs3dG8KiG5b7)
   - [x] Leader onboarding - give role
   - [x] Set the day and time
   - [x] Define the material to be used in study group
   - [x] Request photo for artwork
   - [x] [Request creation of an article about the study group](https://pt.w3d.community/lea_arafah/afinal-de-contas-o-que-e-creative-coding-9j8)
   - [x] Schedule a web3nar about the study group

- [x] Create discord setting
  - [x] create channel
  - [x] create group description
  - [x] create student role
  - [x] create channel button choose your group

- [x] Create marketing assets
  - [ ] ~Banner event discord~
  - [x] Social media artwork
  - [x] Copy description:
    - [x] Discord
    - [ ] ~Youtube~
    - [x] Email
    - [x] Google Calendar

 - [x] Schedule in:
   - [x] Google Calendar
   - [x] Discord
   
- [x] Add to Homepage
- [ ] Add to database to collect attendance

- [x] Publicity
  - [x] Communicate to community "annoucements" discord channel
  - [x] Communicate to whatsapp
  - [x] Publish on social networks
    - [x] Instagram
    - [x] Whatsapp
    - [x] ~Twitter~
    - [x] Linkedin
    - [ ] ~Youtube~

> [!NOTE]  
> create documentation in the gitbook to detail this checklist
