### ISSUE TITLE
Checklist For Study Group Leaders

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#165]
# Leader Checklist

### Before event
- [ ] Share your position in LinkedIn: Study Group Leader at WEB3DEV
- [ ] [Share on social media one day before each event](https://bit.ly/w3b3d3v)
  - [ ] Twitter
  - [ ] LinkedIn
- [ ] Have the content for the group prepared before the event - peer review if necessary
- [ ] Choose your study group in the Study Groups Category

### During Event
- [ ] Start the event in discord
- [ ] Onboard to newcomers explaining how the group works
- [ ] Remember members to put on LinkedIn as an education item
- [ ] Keep asking questions and incentivize participation
- [ ] 5 minutes content revision of last week
- [ ] Create a 1 question quiz for the session and send it to @danicuki
- [ ] share NPS survey Link

### After event

- [ ] Create quizzes on social networks on the subjects of the study groups
