### ISSUE TITLE
Brand Book: Delivery Social Media Assets

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/community-management#172]
# Overview 

A construção de templates para postagens de Social Media como Instagram e X

# Tasks

- [ ] Template de Grupo de Estudos de Tecnologia
- [ ] Template de Grupo de Estudos de Desenvolvimento
- [ ] Template de Grupo de Estudos de Blockchain
- [ ] Template de Webinar
