### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by allluz** [w3b3d3v/community-management#48]

**Comment by allluz** [comment]
**DIVULGAÇÃO DO WEB3NAR**

- [ ] Registro do evento através do [formulário de inscrição](https://pt.w3d.community/realizar-evento);

- [ ] Após o evento ser confirmado pelos líderes da Comunidade, encaminhar briefing de informações registradas no ato de inscrição como Issue para copywriter elaborar descrição do evento e o material gráfico (thumbnails) ser criado. Considera-se também a criação de chamadas para redes sociais, o Discord, e um artigo no Blog com mais detalhes sobre o evento e participantes;

- [ ] Após finalização e revisão do conteúdo para divulgação, realizar agendamento do evento no StreamYard. Geralmente, opta-se em transmitir nos canais do YouTube, X e LinkedIn de modo simultâneo; 

- [ ] Após a obtenção do link do evento por meio do StreamYard em uma das plataformas anteriores, realizar agendamento do evento com data, horário e link oficial da transmissão, no Discord da Comunidade e Agenda de Eventos WEB3 para publicar um chamada no Canal de Avisos e/ou Apps de Mensagens;

- [ ] Após publicação do artigo de divulgação no Blog com vídeo da transmissão anexado (no caso do Youtube), divulgar link do artigo ou o link direto da transmissão junto do material gráfico de divulgação nas demais mídias digitais, que deve ser postado em colaboração com os membros que conduzirão o evento;

**Comment by allluz** [comment]
**CHECKLIST COPY/DESIGN #WEB3NAR**

- [ ] DESCRIÇÃO DO EVENTO;
- [ ] THUMBNAIL DO EVENTO (Discord);
- [ ] THUMBNAIL DO EVENTO (Youtube);
- [ ] THUMBNAIL DO EVENTO (Blogpost);
- [ ] BLOGPOST COM VÍDEO ANEXADO;
- [ ] ARTE FIXA DE DIVULGAÇÃO;
- [ ] LEGENDA PARA LINKEDIN COM LINK UTM (Blogpost);
- [ ] CHAMADA PARA O CANAL DE AVISOS; (Discord/Whatsapp) COM LINK DO EVENTO;
- [ ] LEGENDA PARA INSTAGRAM COM LINK UTM / STORIES (Blogpost);
- [ ] LEGENDA PARA X COM LINK UTM (Blogpost)

**Comment by allluz** [comment]
**CHECKLIST COPY/DESIGN #AGENDA**

- [ ] DESCRIÇÃO DO EVENTO;
- [ ] THUMBNAIL DO EVENTO (Discord);
- [ ] THUMBNAIL DO EVENTO (Blogpost);
- [ ] BLOGPOST COM LINK DO EVENTO;
- [ ] ARTE FIXA DE DIVULGAÇÃO;
- [ ] LEGENDA PARA LINKEDIN COM LINK UTM (Blogpost);
- [ ] CHAMADA PARA O CANAL DE AVISOS; (Discord/Whatsapp) COM LINK DO EVENTO;
- [ ] LEGENDA PARA INSTAGRAM COM LINK UTM / STORIES (Blogpost);
- [ ] LEGENDA PARA X COM LINK UTM (Blogpost)
