### ISSUE TITLE
Checklist Builds

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#68]
https://docs.google.com/document/d/149nkXhI5FDfvdR8VEYWirM1kljg8WQTxiks9h-_v4is/edit#heading=h.yijzjzz6vwa1

**Comment by allluz** [comment]
**Announcement of Build launch**

- [ ] THEME DEFINITION;
- [ ] REVISION OF THE BUILD;
- [ ] ACTIVATION OF MONITORING AND CLASSES;
- [ ] BUILD ON THE HOME PAGE OF THE STUDY PLATFORM;
- [ ] DESCRIPTION OF THE KICKOFF WITH REGISTRATION LINK;
- [ ] KICKOFF THUMBNAIL (Discord, Youtube);
- [ ] KICKOFF LINK (StreamYard).
- [ ] KICKOFF LINK (Discord)
- [ ] KICKOFF THUMBNAIL (Blogpost);
- [ ] BLOGPOST WITH ATTACHED VIDEO AND REGISTRATION LINK;
- [ ] PROMOTE THE TEAM;
- [ ] SEND AN E-MAIL 9 DAYS BEFORE THE KICKOFF;
- [ ] COMMUNITY OUTREACH;
- [ ] REMINDER ON THE DAY OF THE KICKOFF BY E-MAIL;
- [ ] REMINDER TO FINALIZE THE BUILD;
- [ ] FIXED ARTWORK;
- [ ] SHORT VIDEO CALL;
- [ ] CALLS TO SIGN UP FOR PLANNED CONTENT IN THE WEEKS LEADING UP TO THE KICKOFF;
- [ ] LEARNING LINE COUNTDOWN FOR THE WEEK OF THE KICKOFF;;
- [ ] LEGEND FOR LINKEDIN WITH UTM LINK (Blogpost);
- [ ] CALL TO NOTICE CHANNEL; (Discord/Whatsapp) WITH EVENT LINK;
- [ ] LEGEND FOR INSTAGRAM WITH UTM LINK / STORIES (Blogpost);
- [ ] LEGEND FOR X WITH UTM LINK (Blogpost)
