### ISSUE TITLE
Create a roadmap for those who want to start their career as a blockchain developer

### ISSUE THREAD

**Issue by viniblack** [w3b3d3v/community-management#73]
[Blockchain roadmap PT-BR](https://roadmap.sh/r?id=65ae856f0c548122831d7b89)
[Roadmap on the web3dev](https://pt.w3d.community/roadmap-blockchain)
Today there is a blockchain roadmap in EN, we can translate it.
For this first version we want to have the following points:

https://roadmap.sh/r?id=65ae856f0c548122831d7b89

![Image](https://github.com/w3b3d3v/community-management/assets/51183682/b61e1bbb-fba4-444e-ae27-7583541a78da)

**Comment by viniblack** [comment]
# The following points are missing:
## Conhecimento geral de blockchain:
- [x] Storage
- [x] Modelos de mineração e incentivos
- [x] Descentralização vs confiança
- [x] Forking de blockchain
- [x] Criptomoedas
- [x] Carteira Criptográfica (Wallets)
- [x] Blockchains:
  - [x] Solana
  - [x] TON
  - [x] L2 Blockchains
    - [x] Arbitrum
    - [x] Starknet
  - [x] Baseado em EVM:
    - [x] Ethereum
    - [x] Polygon
    - [x] Binance Smart Chain
    - [x] Gnosis Chain
    - [x] Huobi Eco Chain
    - [x] Avalanche
    - [x] Fantom
    - [x] Moonbeam / Moonriver

![Image](https://github.com/w3b3d3v/community-management/assets/51183682/156702ee-d635-4927-89e3-ce1b76f2ac72)

**Comment by viniblack** [comment]
https://pt.w3d.community/roadmap-blockchain
