### ISSUE TITLE
Web3nars checklist

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#79]
# Web3nars scheduling task list

## Before event

Staff:

- [ ] Define the host
- [ ] Define the host support 

Web3nar
- [ ] Define the topic and the guest
- [ ] [Fill in the appointment form](https://docs.google.com/forms/d/e/1FAIpQLSd1NFViqjxrxS73pGz9a8NMxTXYcm8oQFB-WuM8QZ80yK-c2w/viewform?usp=sf_link)
- [ ] Create marketing assets
  - [ ] Banner event discord
  - [ ] Banner youtube
  - [ ] Banner forem
  - [ ] Social media artwork
  - [ ] Copy description
     - [ ] Discord
     - [ ] Youtube
     - [ ] Community Agenda (notion)
     - [ ] Google Calendar
  - [ ] Blog post (forem)
  - [ ] Request short video of guest 
- [ ] Schedule at:
   - [ ] Google Calendar
   - [ ] Discord
   - [ ] Community Agenda (notion)
   - [ ] Streamyard
- [ ] Create the meeting guide
- [ ] Validate all the content and marketing assets with the guest
- [ ] Communicate to community "avisos" discord channel 
- [ ] Communicate to whatsapp
- [ ] Publish on social networks
  - [ ] Instagram
  - [ ] Twitter
  - [ ] Linkedin
  - [ ] Youtube

## During event

~adicionar link do meeting guide~

- [ ] Video countdown
- [ ] Ask for like and share
- [ ] Ask the public to leave feedback in the comments

## After event

- [ ] After two days we analyzed the performance 
- [ ] Collect guest feedback

**Comment by annabida** [comment]
# Host checklist:
* Register with Squad Media
* Onboarding on moderation
* Participate in Chapter calls
* Have recorded or produced at least one video in the community
