### ISSUE TITLE
Checklist study group

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#80]
# Study group scheduling task list

## Before event
- [ ] [Fill in the form](https://forms.gle/dgvGgcs3dG8KiG5b7)
   - [ ] Have a group leader
   - [ ] Set the day and time
   - [ ] Define the material to be used in study group
- [ ] Create marketing assets
  - [ ] Banner event discord
  - [ ] Social media artwork
  - [ ] Copy description:
    - [ ] Discord
    - [ ] Youtube
    - [ ] Community Agenda (notion)
    - [ ] Google Calendar
- [ ] Schedule in:
   - [ ] Google Calendar
   - [ ] Discord
   - [ ] Community Agenda (notion)
- [ ] Communicate to community "annoucements" discord channel
- [ ] Communicate to whatsapp
- [ ] Publish on social networks
  - [ ] Instagram
  - [ ] Twitter
  - [ ] Linkedin
  - [ ] Youtube

## After event

- [ ] Create quizzes on social networks on the subjects of the study groups

### Before event
- [ ] Share your position in LinkedIn: Study Group Leader at WEB3DEV
- [ ] [Share on social media one day before each event](https://bit.ly/w3b3d3v)
  - [ ] Twitter
  - [ ] LinkedIn
- [ ] Have the content for the group prepared before the event - peer review if necessary
- [ ] Choose your study group in the Study Groups Category
### During Event
- [ ] Start the event in discord
- [ ] Onboard to newcomers explaining how the group works
- [ ] Remember members to put on LinkedIn as an education item
- [ ] Keep asking questions and incentivize participation
- [ ] 5 minutes content revision of last week
- [ ] Create a 1 question quiz for the session and send it to @danicuki
- [ ] share NPS survey Link
