### ISSUE TITLE
1st Design Curation for Web3Task

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#94]

**Comment by marcaumdesign** [comment]
# Overview 🌎

It was decided between @piadascripto and @nomadbitcoin the design priority for the Web3Dev main product project, the **[Builds Platform](https://build.w3d.community/courses)**.

As a result, the work on Web3Task will be curatorial in style, where I will suggest and indicate the progress and improvement of the application through meetings and videos.

# Tasks ✅

- [x] Notify Web3Task members of my new work approach
- [x] Write down UX suggestions
- [x] Write down UI suggestions
- [x] Record a video and upload it to the channel

# Design Curation 🔍

## UX 😁

- Sugiro: dar pro usuário a opção de colocar mais de uma carteira (recomendo usar o [RainbowKit](https://www.rainbowkit.com/pt-BR))
> Porque: o usuário as vezes possui outra carteira além da MetaMesk, e esse Kit possui uma função que força o usuário a se conectar 
- Sugiro: avisar pro usuário quando a entrada no formulário é de um tipo inválido (ex: colocar String onde se pede um valor numérico)
> Porque: o usuário perde um tempo ao descobrir que seu método está errado só após ter submetido o formulário
- Sugiro: colocar disponíveis as tasks pros usuários mesmo sem eles conectarem a carteira
> Porque: usuários que estão apenas de passagem ou não tem carteira na Web3 necessitam ver as tasks e recompensas como uma demonstração do aplicativo
- Sugiro: dar o valor em dolar dos valores em ETH nas tasks
> Porque: agilizar o tempo de busca do usuário dos valores
- Sugiro: dar a opção do usuário colocar foto na task


## UI 💻

- Sugiro: criar um footer com as infos da build, discord da web3dev, github e outras informações sobre o participante
- Sugiro: trocar sombras por linhas (mesma cor dos formulários)
- Sugiro: tirar borda pontilhada das tasks


> Requested by: @marcaum-eth
